# Build a Qt project on macOS
name: Build on macOS

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Homebrew
      id: cache-brew
      uses: actions/cache/restore@v5
      with:
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/Cellar/pkg-config
          /opt/homebrew/Cellar/gstreamer
          /opt/homebrew/Cellar/gst-plugins-base
          /opt/homebrew/Cellar/gst-plugins-good
          /opt/homebrew/Cellar/gst-plugins-bad
          /opt/homebrew/Cellar/gst-plugins-ugly
          /opt/homebrew/Cellar/gst-libav
        key: brew-gstreamer-${{ runner.os }}-v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
        version: '5.12.12'
        host: 'mac'
        target: 'desktop'
        install-deps: true
        modules: 'qtwebengine'

    - name: Install dependencies
      if: steps.cache-brew.outputs.cache-hit != 'true'
      run: |
        brew install pkg-config \
          gstreamer \
          gst-plugins-base \
          gst-plugins-good \
          gst-plugins-bad \
          gst-plugins-ugly \
          gst-libav

    - name: Set environment
      run: |
        GST_PREFIX="$(brew --prefix gstreamer)"
        PKG_CONFIG_PATH="${GST_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV

    - name: qmake
      run: qmake .

    - name: make
      run: make -j1

    - name: make check
      run: make check

    - uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: MapMap

#    - name: make distcheck
#      run: make distcheck

    - name: Always cache brew
      if: always() && steps.cache-brew.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.cache-brew.outputs.cache-primary-key }}
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/Cellar/pkg-config
          /opt/homebrew/Cellar/gstreamer
          /opt/homebrew/Cellar/gst-plugins-base
          /opt/homebrew/Cellar/gst-plugins-good
          /opt/homebrew/Cellar/gst-plugins-bad
          /opt/homebrew/Cellar/gst-plugins-ugly
          /opt/homebrew/Cellar/gst-libav
