# Build a Qt project on Windows
name: Build on Windows

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v6
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
        version: '5.12.12'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        install-deps: true
        modules: 'qtwebengine'
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        sdk: 10.0.22621.0
    - name: Install GStreamer
      run: |
        choco install gstreamer gstreamer-devel -y
        echo "GSTREAMER_1_0_ROOT_MSVC_X86_64=C:\Program\ Files\gstreamer\1.0\msvc_x86_64" >> $env:GITHUB_ENV
    - name: qmake
      run: qmake . -spec win32-msvc "GSTREAMER_1_0_ROOT_X86=C:\Program\ Files\gstreamer\1.0\msvc_x86_64\"
    - name: make
      run: nmake
    - name: make check
      run: nmake check

    - name: List files
      run: ls -la

    - uses: actions/upload-artifact@v7
      with:
        path: mapmap*


#    - name: make distcheck
#      run: make distcheck
